"""Add hourly_cost to Equipment

Revision ID: 2be96f3e123e
Revises: 930ae4940037
Create Date: 2026-06-15 20:38:51.489725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be96f3e123e'
down_revision: Union[str, Sequence[str], None] = '930ae4940037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hourly_cost', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('hourly_cost')

    # ### end Alembic commands ###
