"""Add waste_quantity to Preparation and ProductionBatch

Revision ID: 60fed3f60f31
Revises: 2be96f3e123e
Create Date: 2026-06-15 21:55:29.209332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fed3f60f31'
down_revision: Union[str, Sequence[str], None] = '2be96f3e123e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preparations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waste_quantity', sa.Numeric(precision=12, scale=3), nullable=False, server_default='0'))

    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waste_quantity', sa.Numeric(precision=12, scale=3), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.drop_column('waste_quantity')

    with op.batch_alter_table('preparations', schema=None) as batch_op:
        batch_op.drop_column('waste_quantity')

    # ### end Alembic commands ###
