"""add_source_batch_tracking

Revision ID: 6baa46783c5c
Revises: 60fed3f60f31
Create Date: 2026-06-16 21:52:14.716302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6baa46783c5c'
down_revision: Union[str, Sequence[str], None] = '60fed3f60f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_ingredient_uses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_batch_ingredient_uses_purchase_item', 'purchase_items', ['purchase_item_id'], ['id'])

    with op.batch_alter_table('batch_packaging_uses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_batch_packaging_uses_purchase_item', 'purchase_items', ['purchase_item_id'], ['id'])

    with op.batch_alter_table('batch_preparation_uses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_preparation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_batch_preparation_uses_source_prep', 'preparations', ['source_preparation_id'], ['id'])

    with op.batch_alter_table('preparation_ingredient_uses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_prep_ingredient_uses_purchase_item', 'purchase_items', ['purchase_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preparation_ingredient_uses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('purchase_item_id')

    with op.batch_alter_table('batch_preparation_uses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_preparation_id')

    with op.batch_alter_table('batch_packaging_uses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('purchase_item_id')

    with op.batch_alter_table('batch_ingredient_uses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('purchase_item_id')

    # ### end Alembic commands ###
